### ISSUE TITLE
phpseclib version upgrade

### ISSUE THREAD

**Issue by wkopala** [stackkit/laravel-google-cloud-scheduler#21]
I'm having issues continuing to use this package due to it having the requirement of phpseclib locked in at version 2 (conflicts with another package I need). Any chance of getting an update?

**Comment by marickvantuil** [comment]
Thanks, I'll bump that dependency very soon! Feel free to make a PR if you need it sooner.

**Comment by marickvantuil** [comment]
Created a new version `v2.0.2` with phpseclib bumped to 3.x!

**Comment by marickvantuil** [comment]
Thanks, been seeing the same error, so I've downgraded it back to v2 for now. I think there should be a fix coming soon for google-auth-library-php, so I think this upgrade will have to wait until that is done.
