### ISSUE TITLE
Getting "The given OpenID token is not valid" despite iss being present...

### ISSUE THREAD

**Issue by atrauzzi** [stackkit/laravel-google-cloud-scheduler#9]
In the process of setting up this library and I'm getting the following exception:

```
Stackkit\LaravelGoogleCloudScheduler\CloudSchedulerException: The given OpenID token is not valid
#0 Stackkit\LaravelGoogleCloudScheduler\OpenIdVerificator::guardAgainstInvalidOpenIdToken called at [/var/www/html/vendor/stackkit/laravel-google-cloud-scheduler/src/TaskHandler.php:65]
#1 Stackkit\LaravelGoogleCloudScheduler\TaskHandler::authorizeRequest called at [/var/www/html/vendor/stackkit/laravel-google-cloud-scheduler/src/TaskHandler.php:41]
#2 Stackkit\LaravelGoogleCloudScheduler\TaskHandler::handle called at [/var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:48]
#3 Illuminate\Routing\ControllerDispatcher::dispatch called at [/var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php:239]
#4 Illuminate\Routing\Route::runController called at [/var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php:196]
#5 Illuminate\Routing\Route::run called at [/var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:685]
#6 Illuminate\Routing\Router::Illuminate\Routing\{closure} called at [/var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128]
```

My schedule is correctly configured, I've read through https://github.com/stackkit/laravel-google-cloud-scheduler/issues/5, but nothing in there seems to apply or I've already correctly configured. I can also see the `iss` value in my JWT when looking at the exception info that I'm reporting to raygun.

The only thing suspicious to me is that I have some logging in my `Kernel::schedule(Schedule $schedule)` which appears to be output **prior** to the exception above.

Not sure what's going on here, but by everything I can see, it should be working?

**Comment by marickvantuil** [comment]
Can you check what value you have set in the **Audience** field for the scheduled job?

<img width="544" alt="Screenshot 2021-07-13 at 22 46 40" src="https://user-images.githubusercontent.com/647007/125522726-ecc1cd0c-f714-4f69-82cc-2310e7db2a2a.png">

It should be the same as the value set in the environment file:

<img width="830" alt="Screenshot 2021-07-13 at 22 48 21" src="https://user-images.githubusercontent.com/647007/125522771-a853c20f-ca81-4db6-ad03-d42d3545ad3b.png">

Maybe there is a trailing space or something? 

Another option is that the iss claim is not correct, but I don't expect that. Also check if the Laravel config files are cached?

**Comment by atrauzzi** [comment]
Ahhh.  I didn't have `/cloud-scheduler-job` at the end.  Haha, thanks, works like a charm!
